<?php echo $this->doctype(); ?>
<html>
    <head>
        <title>ZF2 Skeleton by AFYM</title>
        <script src="http://code.jquery.com/jquery-migrate-1.1.0.min.js"></script>
    </head>
    <body>
        <h1 style="color: yellowgreen; text-align: center;"> Zend Framework <span style="color: black;">2</span> Simple Skeleton</h1>
        <div style="background-color: oldlace; border : 1px solid black; padding: 20px;">
            <?php echo $this->content ?>
        </div>
    </body>
</html>