<?php echo $this->doctype(); ?>
<html>
    <head>
        <title>ZF2 Skeleton by AFYM</title>
        <?php echo $this->headLink()->prependStylesheet($this->basePath('css/demos.css')) ?>
        <?php echo $this->facesCommonLoad() ?>
        <script type="text/javascript" src="<?php echo $this->basePath('js/jquery/ui/jquery.ui.datepicker.js') ?>"></script>
        
        <script type="text/javascript" src="<?php echo $this->basePath('js/jquery/ui/jquery.ui.button.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath('js/jquery/ui/jquery.ui.spinner.js') ?>"></script>
    </head>
    <body>
        <h1 style="color: yellowgreen; text-align: center;"> Zend Framework <span style="color: black;">2</span> Simple Skeleton</h1>
        <div style="background-color: oldlace; border : 1px solid black; padding: 20px;">
            <?php echo $this->content ?>
        </div>
    </body>
</html>