<!--http://netbeans.org/images_www/articles/portalpack/jsfPortletPalette.gif-->

<form>
    <fieldset>
        <legend>Client</legend>
        Name : <?php echo $this->name ?>
        Surname : <?php echo $this->surname ?>
        Phone : <?php echo $this->phone ?>
        <fieldset>
            <legend>Sports</legend>
            <?php echo $this->sports ?>
        </fieldset>
        <?php echo $this->google ?>
    </fieldset>
</form>